name: Node.js CI

on:
  push:
    branches:
      - master  # Trigger on push to master branch
  pull_request:
    branches:
      - master  # Trigger on pull requests to master branch

jobs:
  build:
    runs-on: ubuntu-latest

    steps:
    - name: Checkout code
      uses: actions/checkout@v2  # Checks out the code

    - name: Set up Node.js
      uses: actions/setup-node@v2
      with:
        node-version: '14'  # Set Node.js version

    - name: Install dependencies
      run: npm install  # Installs dependencies

    - name: Build and start app (optional)
      run: |
        npm start &
        sleep 5  # Wait for app to start
        curl http://localhost:3000  # Make a request to the app

